IngredientのみController->Service->Repositoryの構造化
hita-fttk/simple-recipe-store pull request #14
Opened 2023-05-03 05:31 UTC by hita-fttk

IngredientのみController->Service->Repositoryのアーキテクチャにしました。
「User」と「Recipe」はControllerファイルとServiceファイルとRepositoryファイルのみ作成しております。

データの受け渡しに関しては$idをＵＲＬに渡せるようなコーディングをしております。
詳しくは「ingredient.blade.php」ファイルの<form>タグの中身を参照してください。

そこからIngredientController->IngredientService->IngredientRepository->IngredientModelの流れを想定しています。

2023-05-07 11:53 UTC, hita-fttk commented
具材登録ページを作成し、$request->nameに値を持たせることができるようになった。
次はControllerのstoreメソッドに渡してIngredientModelに登録できる機能を追加する。
ServiceとRepositoryの構造は5/8（月）に実装する。

2023-05-08 11:57 UTC, higaki-takanori requested changes

2023-05-08 11:57 UTC, higaki-takanori commented on simple-recipe-store/routes/web.php
> +Route::get('/ingredient_resister/{id}', function () {
NOT GOOD `/ingredient_resister/{id}`
GOOD `/ingredients/{id}`

2023-05-08 11:57 UTC, higaki-takanori commented on simple-recipe-store/routes/web.php
> +Route::post('/ingredient_store',[IngredientController::class,'store'])->name('ingredient_store');
`register`と`store`の違いは？

2023-05-08 11:57 UTC, higaki-takanori commented on simple-recipe-store/app/Http/Controllers/IngredientController.php
> +    public function store(Request $request)
`store`は何のためのもの？
特に意味がない気がするよ

2023-05-08 11:57 UTC, higaki-takanori commented on simple-recipe-store/app/Http/Controllers/IngredientController.php
> +        // 以下略
？？

2023-05-08 11:57 UTC, higaki-takanori commented on simple-recipe-store/app/Http/Controllers/RecipeController.php
> +<?php
commitは正しい分割をしてね

今回は`ingredient`に関するcommitのはずだから、`recipe`は別のcommitが正しい

2023-05-08 11:57 UTC, higaki-takanori commented on simple-recipe-store/app/Repository/IngredientRepository.php
> +namespace App\Http\Repository;
ディレクトリ構造的に合わせるなら`namespace App\Http\Repository;`はおかしい

2023-05-08 11:57 UTC, higaki-takanori commented on simple-recipe-store/app/Repository/RecipeRepository.php
> +public function index()
？？
リポジトリはDBとのやり取りを記載する場所だから、サービスを呼び出すのはおかしい
ビューを返却するものおかしい

2023-05-08 11:57 UTC, higaki-takanori commented on simple-recipe-store/routes/web.php
> +Route::get('/ingredient_resister',function(){
どうやってviewを返却すべきかについて理解できていない印象を受けた。
今度説明してみて

2023-05-09 14:31 UTC, hita-fttk commented
上記のレビュー以外の懸念点を共有します。
現状、具材の一覧ページを「ingredient.blade.php」をいうファイル名にしているが
具材が複数表示されるページなので
正しくは「ingredients.blade.php」にすべきだという懸念があります。
いかがでしょうか。指摘頂いてから修正します。

2023-05-09 14:59 UTC, higaki-takanori commented
> 上記のレビュー以外の懸念点を共有します。
> 現状、具材の一覧ページを「ingredient.blade.php」をいうファイル名にしているが
> 具材が複数表示されるページなので
> 正しくは「ingredients.blade.php」にすべきだという懸念があります。
> いかがでしょうか。指摘頂いてから修正します。

bladeは意味がわかるファイル名にすべき
具材一覧ならば、「ingredient.list.blade.php」みたいな名前の方がわかりやすいかも
具材登録ならば、「ingredient.store.blade.php」みたいな

ファイル名は適宜考えてみて

2023-05-09 15:21 UTC, hita-fttk commented
5/9の深夜に相談したもの第一弾
Ingredientの登録のみController->Service->Repository->ModelのアーキテクチャにできたのでCommitします。

2023-05-09 15:26 UTC, hita-fttk commented
5/9の深夜に相談したもの第二弾
こちらもブランチ名がおかしいのですがCommitさせていただきました。
しかし
詳細ページはlistメソッド、一覧ページはshowメソッドに修正しようとするのでこのCommitはNGにしてください。

マイグレーションはふと調理器具テーブルを作成しようと思い作成したものです。

2023-05-12 09:59 UTC, higaki-takanori commented on simple-recipe-store/app/Services/IngredientService.php
> +        return $ingredient = $this->ingredientRepository->storeIngredient($ingredientName);
`return $ingredient = $this->ingredientRepository->storeIngredient($ingredientName);`
`return $this->ingredientRepository->storeIngredient($ingredientName);`

今回は、変数を作成する意味はないな

2023-05-12 10:02 UTC, higaki-takanori commented on simple-recipe-store/app/Repository/IngredientRepository.php
> +    public function storeIngredient(string $ingredientName)
修正しなくても良いけど、
関数名 `storeIngredient` -> `createIngredient` の方がわかりやすいかも

2023-05-12 10:03 UTC, higaki-takanori commented on simple-recipe-store/app/Http/Controllers/IngredientController.php
> +        $ingredient->save();
`$ingredient->save();`

これは何？？
あまり意味がない気がする

2023-05-14 05:19 UTC, hita-fttk commented
上記すべての指摘を修正しました。
ご確認のほど、お願い致します。

2023-05-15 14:53 UTC, merged