Feature/recipe resister list show delete
hita-fttk/simple-recipe-store pull request #21
Opened 2023-05-14 14:24 UTC by hita-fttk

Recipe「レシピ」部分のView,Route,Controller,Service,Repository,マイグレーションを作成しました。

recipe.list.blade.phpというファイル名にしようとしましたが
recipe_list.blade.phpにしました。その理由はissuesに記載したので確認をお願いします。

2023-05-15 15:33 UTC, hita-fttk commented
第一弾のコミットでは
Ingredientの登録画面表示のためにControllerにresister_viewメソッドを作成

RecipeのルートをREST型に変更。
Recipeの登録画面表示のためにControllerにresister_viewメソッドを作成

2023-05-15 15:37 UTC, hita-fttk commented
第二弾のコミットでは
レシピの登録画面と3つのリンク先とRecipeのresister_viewメソッドを作成しました。

今後は全員分のレシピ一覧と個人分のレシピ一覧ページを作成予定です。
個人分のレシピ一覧ページは中間テーブルを使用する必要があるとおもうので
わからなければご教授いただきたいです。

2023-05-18 13:40 UTC, higaki-takanori requested changes

2023-05-18 13:40 UTC, higaki-takanori commented on simple-recipe-store/app/Repository/RecipeRepository.php
> +    public function listRecipe()
メソッド名

2023-05-18 13:40 UTC, higaki-takanori commented on simple-recipe-store/routes/web.php
> +Route::get('/recipe.list',[RecipeController::class,'list'])->name('recipe.list');
NG: `Route::get('/recipe.list',[RecipeController::class,'list'])->name('recipe.list');`
OK: `Route::get('/recipes',[RecipeController::class,'list'])->name('recipe.list');`

2023-05-18 13:40 UTC, higaki-takanori commented on simple-recipe-store/routes/web.php
> +Route::get('/recipe.show/{id}',[RecipeController::class,'show'])->name('recipe.show');
NG: `Route::get('/recipe.show/{id}',[RecipeController::class,'show'])->name('recipe.show');`
OK: `Route::get('/recipes/{id}',[RecipeController::class,'show'])->name('recipe.show');`

2023-05-18 13:40 UTC, higaki-takanori commented on simple-recipe-store/routes/web.php
> +Route::get('/recipe.show/{id}',[RecipeController::class,'show'])->name('recipe.show');
他のルーティングも直して

2023-05-18 13:41 UTC, higaki-takanori requested changes
直して

2023-05-18 13:41 UTC, higaki-takanori requested changes
直して

2023-05-18 14:29 UTC, hita-fttk commented
上記のルート変更とそれに伴うリンクの変更をしました。
確認お願いします。

2023-05-18 14:30 UTC, higaki-takanori requested changes
ここも直して

2023-05-18 14:30 UTC, higaki-takanori commented on simple-recipe-store/routes/web.php
> +Route::get('/ingredients/new',[IngredientController::class,'store_view'])->name('ingredient.store_view');
`IngredientController`のstore_viewは直さなくて良いの？

2023-05-18 14:32 UTC, hita-fttk commented
送信しました。

2023-05-18 14:33 UTC, merged