具材登録のためのリンク名を変更
hita-fttk/simple-recipe-store pull request #26
Opened 2023-05-24 16:39 UTC by hita-fttk

具材の登録に関する変更なのでコミットを分けさせていただきます。

2023-05-24 16:43 UTC, hita-fttk commented
fetchAlltoRecipe()の箇所は仮で決めたのでご指摘をお願いします。
recipe_resister.blade.phpに記載のjavascript箇所に関してはIngredientの部分のみ実装しました。
問題なければkitchentoolとcookingも記載します。

2023-05-26 14:28 UTC, higaki-takanori requested changes
直して
考えながらファイト

2023-05-26 14:28 UTC, higaki-takanori commented on simple-recipe-store/app/Http/Controllers/RecipeController.php
> +        $recipeList = $this->recipeService->fetchAlltoRecipe();
自分で考えれるようになった方が良いよ
参考までに
`fetchRecipeList`
とかかね

2023-05-26 14:28 UTC, higaki-takanori commented on simple-recipe-store/app/Repository/RecipeRepository.php
> +    public function fetchAlltoRecipe()
レシピリポジトリで材料とか調理器具とかを取得するのは良くない
材料を取得したいなら材料リポジトリで取得する。
recipeListはレシピサービスで作成するイメージ

2023-05-26 14:28 UTC, higaki-takanori commented on simple-recipe-store/app/Services/RecipeService.php
> +        return $this->recipeRepository->fetchAlltoRecipe();
```
$ingredients = this->ingredientsRepository->fetchIngredient();
$kitchentoos = ...
$cookings = ...
$recipeList = [
....
];
```

こんなイメージ

2023-05-26 15:10 UTC, hita-fttk commented
Javascriptの拡張により、IngredientId、KitchenToolId、CookingIdをRequestにて渡すことに成功。
メソッド名についても要素＝Elementの解釈で変更した。
各テーブルの情報を取得するのを各Repository内で行い、「RecipeService」ですべてを取得する仕様に変更した。

2023-05-26 15:21 UTC, higaki-takanori approved these changes
修正して

2023-05-26 15:21 UTC, higaki-takanori commented on simple-recipe-store/app/Http/Controllers/RecipeController.php
> +        $recipeList = $this->recipeService->fetchRecipeElement();
そもそもレシピを取得するのではなく、
材料、調理器具などを取得する形にする方がシンプルでわかりやすい

compact()に材料、調理器具リストなどを格納する形

2023-05-26 15:23 UTC, higaki-takanori requested changes

2023-05-26 15:23 UTC, higaki-takanori commented on simple-recipe-store/app/Services/RecipeService.php
> +    public function __construct(RecipeRepository $recipeRepository,IngredientRepository $ingredientRepository,KitchenToolRepository $kitchentoolRepository,CookingRepository $cookingRepository)
修正しなくて良いけど、見にくいね

2023-05-29 13:02 UTC, hita-fttk commented
上記2つの指摘を修正しました。

2023-05-29 13:09 UTC, higaki-takanori requested changes
直して

2023-05-29 13:09 UTC, higaki-takanori commented on simple-recipe-store/app/Services/IngredientService.php
> +        return $ingredients = $this->ingredientRepository->fetchIngredientList();
変数に入れる意味は？
`return $ingredients = $this->ingredientRepository->fetchIngredientList();`
これで十分ではない？同じ書き方をずっとしているけど、理由があってしている？
`return $this->ingredientRepository->fetchIngredientList();`

2023-05-29 13:09 UTC, higaki-takanori requested changes
直して

2023-05-29 13:14 UTC, hita-fttk commented
return時に変数に入れるのは私の感性です。
直します。

2023-05-29 13:16 UTC, higaki-takanori commented
> return時に変数に入れるのは私の感性です。 直します。

すごく悪いことではないんやけど、可読性が下がるので意味がないならやめた方が良いよ

2023-05-29 13:17 UTC, merged